# Generated by Django 3.0.6 on 2020-07-12 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Winner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stupass', models.ImageField(default='Not Available', upload_to='')),
                ('stuname', models.CharField(max_length=50)),
            ],
        ),
    ]
