# Generated by Django 3.0.6 on 2020-07-23 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Winner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_logo', models.ImageField(default='Not Available', upload_to='home/')),
                ('team_name', models.CharField(default='Not Available', max_length=50)),
            ],
        ),
    ]
