# Generated by Django 3.0.6 on 2020-07-12 23:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='winner',
            old_name='stupass',
            new_name='team_img',
        ),
        migrations.RenameField(
            model_name='winner',
            old_name='stuname',
            new_name='team_name',
        ),
    ]
