# Generated by Django 3.0.6 on 2020-07-14 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Daily',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('d_date', models.DateField()),
                ('d_type', models.CharField(max_length=5)),
                ('d_fees', models.DecimalField(decimal_places=2, max_digits=7)),
                ('d_tgames', models.IntegerField()),
            ],
        ),
    ]
