# Generated by Django 3.0.6 on 2020-07-15 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Monthly',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('m_date', models.DateField()),
                ('m_type', models.CharField(max_length=5)),
                ('m_fees', models.DecimalField(decimal_places=2, max_digits=7)),
                ('m_tgames', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Weekly',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('w_date', models.DateField()),
                ('w_type', models.CharField(max_length=5)),
                ('w_fees', models.DecimalField(decimal_places=2, max_digits=7)),
                ('w_tgames', models.IntegerField()),
            ],
        ),
    ]
