# Generated by Django 3.0.6 on 2020-07-16 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0002_monthly_weekly'),
    ]

    operations = [
        migrations.CreateModel(
            name='Djoin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dj_date', models.DateField()),
                ('dj_time', models.TimeField()),
                ('dj_cid', models.IntegerField()),
                ('dj_tname', models.CharField(max_length=50)),
                ('dj_lpname', models.CharField(max_length=50)),
                ('dj_spname', models.CharField(max_length=50)),
                ('dj_tpname', models.CharField(max_length=50)),
                ('dj_fupname', models.CharField(max_length=50)),
                ('dj_fipname', models.CharField(max_length=50)),
                ('dj_wnum', models.IntegerField()),
                ('dj_pbss', models.ImageField(upload_to='djoin/pss/')),
                ('dj_tlogo', models.ImageField(default='Not Available', upload_to='djion/logo/')),
            ],
        ),
    ]
