# Generated by Django 3.0.6 on 2020-07-16 01:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0003_djoin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='djoin',
            old_name='dj_cid',
            new_name='cid',
        ),
        migrations.RenameField(
            model_name='djoin',
            old_name='dj_date',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='djoin',
            old_name='dj_fipname',
            new_name='fifth_pname',
        ),
        migrations.RenameField(
            model_name='djoin',
            old_name='dj_fupname',
            new_name='fourth_pname',
        ),
        migrations.RenameField(
            model_name='djoin',
            old_name='dj_lpname',
            new_name='leader_pname',
        ),
        migrations.RenameField(
            model_name='djoin',
            old_name='dj_pbss',
            new_name='pay_ss',
        ),
        migrations.RenameField(
            model_name='djoin',
            old_name='dj_spname',
            new_name='second_pname',
        ),
        migrations.RenameField(
            model_name='djoin',
            old_name='dj_tlogo',
            new_name='team_logo',
        ),
        migrations.RenameField(
            model_name='djoin',
            old_name='dj_tname',
            new_name='team_name',
        ),
        migrations.RenameField(
            model_name='djoin',
            old_name='dj_tpname',
            new_name='third_pname',
        ),
        migrations.RenameField(
            model_name='djoin',
            old_name='dj_time',
            new_name='time',
        ),
        migrations.RenameField(
            model_name='djoin',
            old_name='dj_wnum',
            new_name='whats_num',
        ),
    ]
