# Generated by Django 3.0.6 on 2020-07-16 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0005_auto_20200716_0203'),
    ]

    operations = [
        migrations.AddField(
            model_name='djoin',
            name='email',
            field=models.EmailField(default='Not Available', max_length=254),
        ),
        migrations.AlterField(
            model_name='djoin',
            name='team_logo',
            field=models.ImageField(default='Not Available', upload_to='djoin/logo/'),
        ),
    ]
