# Generated by Django 3.0.6 on 2020-07-20 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0006_auto_20200716_0423'),
    ]

    operations = [
        migrations.AlterField(
            model_name='djoin',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
