# Generated by Django 3.0.6 on 2020-07-20 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0007_auto_20200720_0143'),
    ]

    operations = [
        migrations.CreateModel(
            name='TGS_Weeks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('match_type', models.CharField(max_length=5)),
                ('fees', models.DecimalField(decimal_places=2, max_digits=7)),
                ('total_games', models.IntegerField()),
            ],
        ),
    ]
