# Generated by Django 3.0.6 on 2020-07-20 02:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0008_tgs_weeks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='djoin',
            name='date',
        ),
        migrations.RemoveField(
            model_name='djoin',
            name='time',
        ),
        migrations.AddField(
            model_name='djoin',
            name='date_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
