# Generated by Django 3.0.6 on 2020-07-23 05:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0009_auto_20200720_0240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='djoin',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='djoin',
            name='team_logo',
            field=models.ImageField(blank=True, null=True, upload_to='djoin/logo/'),
        ),
        migrations.AlterField(
            model_name='djoin',
            name='whats_num',
            field=models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(regex='^\\d{10}$')]),
        ),
    ]
