# Generated by Django 3.0.6 on 2020-07-20 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0009_auto_20200720_0240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='djoin',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='djoin',
            name='team_logo',
            field=models.ImageField(blank=True, null=True, upload_to='djoin/logo/'),
        ),
    ]
