# Generated by Django 3.0.6 on 2020-07-23 04:31

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0010_auto_20200720_0316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='djoin',
            name='whats_num',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None),
        ),
    ]
