# Generated by Django 3.0.6 on 2020-07-23 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0012_auto_20200723_0633'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tgsw_join',
        ),
    ]
