# Generated by Django 3.0.6 on 2020-07-23 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0012_auto_20200723_0434'),
    ]

    operations = [
        migrations.AlterField(
            model_name='djoin',
            name='whats_num',
            field=models.CharField(max_length=10),
        ),
    ]
