# Generated by Django 3.0.6 on 2020-07-23 05:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0013_auto_20200723_0503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='djoin',
            name='whats_num',
            field=models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(regex='^\\d{10}$')]),
        ),
    ]
